---
ds389:
  container_name: "389ds"
  root_dn: "cn=Directory Manager"
  root_password: "ChangeMe123!"
  suffix: "dc=example,dc=com"

ds389_ldap_port: 389

ds389_ldap_service_account:
  username: "ldap-svc"
  password: "ChangeMe123!"
